### ISSUE TITLE
Delete Any Unused Samples

### ISSUE THREAD

**Issue by rychen58** [CIDARLAB/damplab-aquarium#17]
**Please identify the user roles that your feature request relates to?**
Name of user role(s) for whom feature is relevant.
Ex. researcher, lab manager, technician, developer, system administrator
Users of Aquarium, people who submit and create designs, can be researchers, lab managers, technicians, and system administrators.

**What is the task you want to perform?**
Give a clear and concise description of the task the feature is meant to support.
Ex. "I want to find a sample that I used on a particular date..."
Samples that are currently existing in the Aquarium Sample Inventory that are either created by mistakes, created with the wrong sample types, samples that were created but never used, and samples that are no longer useful, need to be deleted to unclog the sample inventory. 

**What is the goal you want to achieve with the feature?**
Give a clear and concise description of the reason why the feature is needed.
Ex. "I need to track down the possible source of an error"
Unclog the sample inventory

**Additional context**

**Comment by bjkeller** [comment]
This would be an aquarium detail. I've linked an issue to this one, so this can be closed.

**Comment by bjkeller** [comment]
@rychen58 as a short term fix, this could be dealt with by running code in the console to remove these from the database.  Let me know if you want to do this.

**Comment by rychen58** [comment]
Yes, that would be helpful.
