### ISSUE TITLE
[FEATURE] Merging two databases with unique Protocols

### ISSUE THREAD

**Issue by zamsam** [CIDARLAB/damplab-aquarium#18]
**Please identify the user roles that your feature request relates to?**
lab manager, developer, and system administrator

**What is the task you want to perform?**
I want to be able to merge two completely databases (each containing different protocols, meaning different sets of codes and samples) into a single database. 

**What is the goal you want to achieve with the feature?**
This situation happens when developers generate new protocols in their local aquarium instances, then they want to transfer these protocols to the server instance without having to do it one by one manually.

**Additional context**

**Comment by bjkeller** [comment]
You should be able to do this by exporting protocols from the developer instance and importing into the lab instance.

**Comment by bjkeller** [comment]
I would suggest closing this.
