### ISSUE TITLE
Sharing Protocols

### ISSUE THREAD

**Issue by taylorschissel** [CIDARLAB/damplab-aquarium#23]
**Please identify the user roles that your feature request relates to?**
researcher, lab manager, technician, developer

**What is the task you want to perform?**
We would like a way to be able to easily transport protocols written on one person's local Aquarium designer tab to another user's local Aquarium. 

**What is the goal you want to achieve with the feature?**
We would like to expedite the process of sharing work-in-progress or new protocols without having to screenshot the definitions page and email that screenshot along with the Ruby file each time, which has been our current method.

**Additional context**
Using the "export workflow" with downloading a .aq folder did not work when tested between two lab technicians. The error we received was that our computers do not have a way to open a .aq file, and without opening the files, we could not load them into our local version of Aquarium.

**Comment by bjkeller** [comment]
Did you use the Import dialog in Aquarium?

<img width="316" alt="Screen Shot 2020-04-20 at 12 34 16 PM" src="https://user-images.githubusercontent.com/5479869/79792203-5ad0df00-8303-11ea-93ad-45922051a1eb.png">
