### ISSUE TITLE
Unable to run Aq instance locally from latest commits

### ISSUE THREAD

**Issue by dany-fu** [CIDARLAB/damplab-aquarium#6]
## Summary & Context

Renaming deployment variables from commit `a20393e364978d2a6a1991efd5d5e251fa9f7751`  "Production Requirements added for DAMPLAB" disabled the ability to run Aquarium instance locally 

## Expected Behavior

User should be able to pull the repo and run a local instance of Aquarium 

## Current Behavior

`Initialization failed with Mysql2::Error::ConnectionError, message: Unknown MySQL server host 'add host here' (-2)`

## Possible Solution

Check out the branch one commit prior
`git checkout b8e2f53c0b3ea7cf26e10a2f7f4d4ef7977f0789`

## Steps to Reproduce

1. Clone repo
2. Checkout `damplab-latest` branch
3. `docker-compose up --build`
4.

**Comment by rkrishnasanka** [comment]
I guess I can reset the branch to the previous commit and create a production branch with the changes I've made.
